language: python
matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      python: pypy3.5
      env:
        - UBUNTU=trusty
        - NOMYPY=true
    - os: linux
      dist: trusty
      python: 3.4
      env:
        - UBUNTU=trusty
    - os: linux
      dist: precise
      python: 3.4
      env:
        - UBUNTU=precise
    - os: linux
      dist: trusty
      python: 3.5
      env:
        - UBUNTU=trusty
    - os: linux
      dist: precise
      python: 3.5
      env:
        - UBUNTU=precise
    - os: linux
      dist: trusty
      python: 3.6
      env:
        - UBUNTU=trusty
    - os: linux
      dist: precise
      python: 3.6
      env:
        - UBUNTU=precise
    - os: linux
      dist: precise
      python: pypy3.5
      env:
        - UBUNTU=precise
        - NOMYPY=true
    - os: linux
      dist: trusty
      python: "3.7-dev"
      env:
        - UBUNTU=trusty
    - os: linux
      dist: precise
      python: "3.7-dev"
      env:
        - UBUNTU=precise
#  allow_failures:
    - os: linux
      dist: precise
      python: pypy3.5
      env:
        - UBUNTU=precise
        - NOMYPY=true
    - os: linux
      dist: trusty
      python: "3.7-dev"
      env:
        - UBUNTU=trusty
    - os: linux
      dist: precise
      python: "3.7-dev"
      env:
        - UBUNTU=precise
    - os: linux
      dist: trusty
      python: 3.6
      env:
        - UBUNTU=trusty
    - os: linux
      dist: precise
      python: 3.6
      env:
        - UBUNTU=precise

install: bash ./install.sh
# pip collective.checkdocs && setup.py checkdocs
script: bash ./run.sh
after_success:
  - coveralls
