language: python
matrix:
  include:
    - os: linux
      dist: trusty
      python: 3.5
      env:
        - BUILD=true
        - UBUNTU=trusty
    - os: linux
      dist: precise
      python: 3.5
      env:
        - BUILD=true
        - UBUNTU=precise
#    - os: linux
#      dist: precise
#      python: pypy3
install: "pip install coverage python-coveralls"
script: python setup.py build && coverage run sos/tests.py && coverage html && coverage annotate sos/tests.py
after_success:
  - coveralls
