# https://ci.appveyor.com/tools/validate-yaml
# http://www.yamllint.com/
build_script:
  - cmd: "python setup.py clean build test --mypy && coverage run --branch --debug=sys --source=sos sos/tests.py && coverage html && coverage annotate sos/tests.py"
clone_script:
  - cmd: "git clone https://github.com/ArneBachmann/sos .\\"
deploy: false
environment:
  PYTHONDONTWRITEBYTECODE: true
  matrix:
#    - PYTHON_VERSION: 2.7
    - PYTHON_VERSION: 3.3
      platform: x86  # PyYAML dependency doesn't run on x64 for some reason
    - PYTHON_VERSION: 3.4
      platform: x86
    - PYTHON_VERSION: 3.4
      platform: x64
    - PYTHON_VERSION: 3.5
      platform: x86
    - PYTHON_VERSION: 3.5
      platform: x64
    - PYTHON_VERSION: 3.6
      platform: x86
    - PYTHON_VERSION: 3.6
      platform: x64
init:
  - "set PY_VER=%PYTHON_VERSION:.=%"
  - "set PYTHON=C:\\PYTHON%PY_VER%"
  - "if %PLATFORM%==x64 (set PYTHON=%PYTHON%-x64)"
  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
install:
  - cmd: "python --version"
  - cmd: "pip install --upgrade appdirs chardet configr wcwidth coconut coverage python-coveralls"
skip_branch_with_pr: true
version: "{build}.{branch}"
