# Check file:
#   https://ci.appveyor.com/tools/validate-yaml
#   http://www.yamllint.com/

build_script:
  # https://mnaoumov.wordpress.com/2015/01/11/execution-of-external-commands-in-powershell-done-right/
#      $ErrorActionPreference = "SilentlyContinue"
  - ps: |
      try {
        if ($isLinux) { ./run.sh } else { cmd /c ".\run.bat 2>&1" | % { "$_" } }
      } catch {
        if ($LastExitCode -ne 0) { "Last exit code: $LastExitCode"; $error.Clear(); exit $LastExitCode } else { $error.Clear(); exit 0 }
      }
clone_script:
  - cmd: "git clone https://github.com/ArneBachmann/sos .\\"
deploy: false
environment:
  PYTHONDONTWRITEBYTECODE: true
  matrix:
    - PYTHON_VERSION: 3.6
      platform: x64
      image: Visual Studio 2013
    - PYTHON_VERSION: 3.6
      platform: x64
      image: ubuntu
    - PYTHON_VERSION: 3.4
      platform: x86
      image: Visual Studio 2013
    - PYTHON_VERSION: 3.4
      platform: x86
      image: ubuntu
    - PYTHON_VERSION: 3.4
      platform: x64
      image: Visual Studio 2013
    - PYTHON_VERSION: 3.4
      platform: x64
      image: ubuntu
    - PYTHON_VERSION: 3.5
      platform: x86
      image: Visual Studio 2013
    - PYTHON_VERSION: 3.5
      platform: x86
      image: ubuntu
    - PYTHON_VERSION: 3.5
      platform: x64
      image: Visual Studio 2013
    - PYTHON_VERSION: 3.5
      platform: x64
      image: ubuntu
    - PYTHON_VERSION: 3.6
      platform: x86
      image: Visual Studio 2013
    - PYTHON_VERSION: 3.6
      platform: x86
      image: ubuntu
#    - PYTHON_VERSION: 2.7
#      platform: x86
#    - PYTHON_VERSION: 2.7
#      platform: x64
    - PYTHON_VERSION: 3.3
      platform: x86
      NOMYPY: true
    - PYTHON_VERSION: 3.3
      platform: x64
      NOMYPY: true
matrix:
  allow_failures:
    - PYTHON_VERSION: 3.3
      platform: x86
      NOMYPY: true
    - PYTHON_VERSION: 3.3
      platform: x64  # PyYAML dependency doesn't run on x64 for some reason
      NOMYPY: true
init:
  - "set PY_VER=%PYTHON_VERSION:.=%"
  - "set PYTHON=C:\\PYTHON%PY_VER%"
  - "if %PLATFORM%==x64 (set PYTHON=%PYTHON%-x64)"
  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
install:
  - cmd: "python --version"
  - ps: |
      if ($isLinux) { ./install.sh } else { cmd /c .\install.bat 2>&1 | % { "$_" } }
skip_branch_with_pr: true
version: "{build}.{branch}"
